### ISSUE TITLE
Digest thread is tracking its own comments

### ISSUE THREAD

**Issue by damithc** [nus-oss/GithubDigest#12]
e.g., https://github.com/damithc/foo/issues/115#issuecomment-1576338632

**Comment by Eclipse-Dominator** [comment]
Is this caused by manually changing the settings file, since by right it should automatically add the relevant issue number to the ignore list?

**Comment by damithc** [comment]
I did not change the setting file. The ignore list was empty from the start. I can delete the settings file. Will that reset everything?

**Comment by damithc** [comment]
Also, why do you need the digest thread number to be in the `ignore_lis`? `target_issue` should be enough to identify the digest thread, right?

**Comment by Eclipse-Dominator** [comment]
> I did not change the setting file. The ignore list was empty from the start. I can delete the settings file. Will that reset everything?

Yes, it will reset everything.

> Also, why do you need the digest thread number to be in the ignore_lis? target_issue should be enough to identify the digest thread, right?

Yes, I will make the change to check for the `issue id` instead of number.
