### ISSUE TITLE
Tweak settings file

### ISSUE THREAD

**Issue by damithc** [nus-oss/GithubDigest#19]
Suggested:
```json
{
    "observed_repo": "",
    "host_repo": "damithc/foo",
    "digest_issue": "I_kwDOBbGdF85nvcKj",
    "ignored_issues": []
}
```

**Comment by Eclipse-Dominator** [comment]
For now `observed_repo` and `host_repo` are no longer saved as they are given as an input to the github action so it is not necessary to save them for now.
